# Generated by Django 5.2.5 on 2026-02-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
