# Generated by Django 5.2.5 on 2026-02-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0002_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='more_info_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
