# Generated by Django 5.2.5 on 2026-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0005_movie_description_en_movie_description_gu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_gu',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_hi',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_gu',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_hi',
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(max_length=50),
        ),
    ]
