# Generated by Django 5.2.5 on 2026-02-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0006_remove_movie_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_hindi',
            field=models.BooleanField(default=False),
        ),
    ]
