# Generated by Django 5.2.5 on 2026-02-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0007_movie_is_hindi'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='top_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
