# Generated by Django 5.2.5 on 2026-02-24 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0010_remove_movie_more_info_link_remove_movie_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='more_info_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='watch_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ExtraVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('quality', models.CharField(blank=True, max_length=50, null=True)),
                ('is_trailer', models.BooleanField(default=False)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_videos', to='krexapp.movie')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
