# Generated by Django 5.2.5 on 2026-02-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0011_movie_more_info_link_movie_video_movie_watch_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='trailers/'),
        ),
    ]
