# Generated by Django 5.2.5 on 2026-02-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0012_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_english',
            field=models.BooleanField(default=False),
        ),
    ]
