# Generated by Django 5.2.5 on 2026-02-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0013_movie_is_english'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraVideo',
        ),
    ]
