# Generated by Django 5.2.5 on 2026-02-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0014_delete_extravideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TvShows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster', models.ImageField(upload_to='posters/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('trailer', models.FileField(blank=True, null=True, upload_to='trailers/')),
                ('release_year', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_hindi', models.BooleanField(default=False)),
                ('is_english', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('watch_link', models.URLField(blank=True, null=True)),
                ('more_info_link', models.URLField(blank=True, null=True)),
                ('top_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
