# Generated by Django 5.2.5 on 2026-02-26 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0015_tvshows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=1)),
                ('episode_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='episodes/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episode_thumbnails/')),
                ('tvshow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='krexapp.tvshows')),
            ],
            options={
                'ordering': ['season', 'episode_number'],
            },
        ),
    ]
