# Generated by Django 5.2.5 on 2026-02-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('krexapp', '0017_alter_watchlist_unique_together_watchlist_tvshow_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tvshows',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('tvshow', 'season', 'episode_number')},
        ),
    ]
